application: pingularity
version: 1
runtime: python
api_version: 1

handlers:
- url: /admin/.*
  login: admin
  script: main.py
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: .*
  script: main.py

builtins:
- datastore_admin: on